# Generated by Django 2.2.1 on 2019-09-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190927_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upanddown',
            old_name='id_up',
            new_name='is_up',
        ),
    ]
